#!/usr/bin/env python
"""Phase-1a (k-Wave): run the classical frontier on k-Wave FMC cubes.

Same analysis as scripts/run_frontier.py, but loads cubes generated by k-Wave
(finite-size SDHs) instead of the analytic point-scatterer model. The point of the
probe: on realistic physics the analytic steering dictionary is mis-specified, so
steer_oracle is no longer ~0 and a genuine, unfilled gap appears.

Usage:
    python scripts/run_frontier_kwave.py --data-dir kwave_npz
"""
from __future__ import annotations

import argparse
import csv
import glob
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fmcfast import LinearArray, metrics
from fmcfast.baselines import (reconstruct_joint_lowrank, reconstruct_naive,
                               reconstruct_nystrom, reconstruct_steering_oracle)
from fmcfast.freqdomain import scene_eff_rank
from fmcfast.sampling import observed_mask, uniform_tx_set

NYSTROM_GRID = [{"rank": r, "rcond": rc} for r in (2, 4, 8, 12, 16)
                for rc in (1e-8, 1e-4, 1e-2)]
JOINT_GRID = [{"lam_rel": l} for l in (0.01, 0.05, 0.15)]


def oracle(method_fn, grid, cube, S, obs, fkw, extra=()):
    best = None
    for hp in grid:
        rec = method_fn(cube, S, *extra, **fkw, **hp)
        v = metrics.band_nrmse_blocks(rec, cube, obs, **fkw)["nrmse_unobs"]
        if best is None or v < best:
            best = v
    return best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default="kwave_npz")
    ap.add_argument("--out", default="results/frontier_kwave.csv")
    args = ap.parse_args()

    files = sorted(glob.glob(os.path.join(args.data_dir, "*.npz")))
    if not files:
        raise SystemExit(f"no .npz cubes in {args.data_dir}")
    k_set = [16, 8, 6, 4]
    rows = []

    for path in files:
        d = np.load(path)
        cube = d["cube"].astype(float)
        defs = d["defects"]
        c, fs, f0 = float(d["c0"]), float(d["fs"]), float(d["f0"])
        n = int(d["n_elements"])
        arr = LinearArray(n, float(d["pitch"]))
        fkw = dict(fs=fs, f0=f0, frac_bw=0.6)
        defects = [(float(x), float(z), 1.0) for x, z, r in defs]
        eff = scene_eff_rank(cube, fs, f0, 0.6)
        name = os.path.basename(path)
        for K in k_set:
            S = uniform_tx_set(n, K)
            obs = observed_mask(n, S)
            mn = metrics.band_nrmse_blocks(reconstruct_naive(cube, S), cube, obs, **fkw)["nrmse_unobs"]
            ny = oracle(reconstruct_nystrom, NYSTROM_GRID, cube, S, obs, fkw)
            jl = oracle(reconstruct_joint_lowrank, JOINT_GRID, cube, S, obs, fkw)
            st = metrics.band_nrmse_blocks(
                reconstruct_steering_oracle(cube, S, defects, arr, c=c, **fkw),
                cube, obs, **fkw)["nrmse_unobs"]
            base = dict(file=name, n_def=len(defects), eff_rank=eff, n_tx=int(S.size),
                        accel_hmc=(n / S.size) / 2.0)
            for m, v in (("naive", mn), ("nystrom", ny), ("joint_lr", jl), ("steer_oracle", st)):
                rows.append(dict(base, method=m, nrmse_unobs=v))
        print(f"{name}: n_def={len(defects)} eff_rank={eff}", flush=True)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    cols = ["file", "n_def", "eff_rank", "n_tx", "accel_hmc", "method", "nrmse_unobs"]
    with open(args.out, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow({k: r[k] for k in cols})
    print(f"\nWrote {len(rows)} rows -> {args.out}\n")

    print("median band_nrmse on UNOBSERVED block (k-Wave data), by acceleration:")
    accels = sorted({(64 // k) // 2 for k in k_set})
    hdr = " | ".join(f"{a:>6.1f}x" for a in accels)
    print(f"{'method':>13} | {hdr}")
    for method in ("naive", "nystrom", "joint_lr", "steer_oracle"):
        cells = []
        for a in accels:
            vs = [r["nrmse_unobs"] for r in rows if r["method"] == method and abs(r["accel_hmc"] - a) < 0.3]
            cells.append(f"{np.median(vs):>6.3f} " if vs else f"{'-':>7}")
        print(f"{method:>13} | " + " | ".join(cells))


if __name__ == "__main__":
    main()
